correcciones en los script para lanzar la primer version!

diff --git a/debian/update-firefox b/debian/update-firefox
--- a/debian/update-firefox
+++ b/debian/update-firefox
@@ -1,8 +1,34 @@
 #!/bin/bash
 
+#filtro para la barra del wget
+progressfilt ()
+{
+    local flag=false c count cr=$'\r' nl=$'\n'
+    while IFS='' read -d '' -rn 1 c
+    do
+        if $flag
+        then
+            printf '%c' "$c"
+        else
+            if [[ $c != $cr && $c != $nl ]]
+            then
+                count=0
+            else
+                ((count++))
+                if ((count > 1))
+                then
+                    flag=true
+                fi
+            fi
+        fi
+    done
+}
+
+failed=0
 work_dir=`mktemp -d --suffix=.update-firefox`
 moz_url='http://ftp.mozilla.org/pub/mozilla.org/firefox/releases/latest'
-wget -O "$work_dir/MD5SUMS" "$moz_url/MD5SUMS"
+echo "Descargando archivo de versiones"
+wget -q --show-progress -O "$work_dir/MD5SUMS" "$moz_url/MD5SUMS"
 
 moz_lang=`echo $LANG | cut -f 1 -d . | sed s/_/-/`
 
@@ -14,17 +40,34 @@ moz_path=`echo $moz_link | cut -f 2 -d " "`
 moz_file=`basename $moz_path`
 
 echo "$moz_md5 $work_dir/$moz_file" >> "$work_dir/VERIFY.MD5"
-wget -O "$work_dir/$moz_file" "$moz_url/$moz_path"
-md5sum -c "$work_dir/VERIFY.MD5"
-
+echo "Descargando $moz_file...Aguarde un momento..."
+wget -q --show-progress -O "$work_dir/$moz_file" "$moz_url/$moz_path" 
 if [ $? = 0 ]; then
-    echo "md5sum OK"
-    rm -rf /opt/firefox
-    tar xvjf "$work_dir/$moz_file" -C "$work_dir"
-    mv "$work_dir/firefox" /opt    
-    rm -rf "$work_dir"
-    echo "Instalacion finalizada"
+
+    #Archivo descargado, comprobar md5
+    echo "Verificando MD5"
+    md5sum -c "$work_dir/VERIFY.MD5"
+
+    if [ $? = 0 ]; then
+        echo "md5sum OK"
+        echo "Eliminado version anterior"
+        rm -rf /opt/firefox
+        echo "Descomprimiendo $moz_file...Aguarde un momento mas..."
+        tar xjf "$work_dir/$moz_file" -C "$work_dir"
+        mv "$work_dir/firefox" /opt    
+    else
+        echo "md5sum ERROR"
+        failed=1
+    fi
 else
-    echo "md5sum ERROR"
+    echo "No se puede descargar el archivo $moz_file."
+    failed=1
+fi
+
+if [ $failed = 0 ]; then
+    rm -rf "$work_dir"
+    echo "Instalación finalizada"
+else
     echo "El directorio temporal de trabajo no fue eliminado para que puedas revisar el problema: $work_dir"
 fi
+
