mejor tolerancia a problemas de conexion

diff --git a/debian/update-firefox b/debian/update-firefox
--- a/debian/update-firefox
+++ b/debian/update-firefox
@@ -1,67 +1,54 @@
 #!/bin/bash
 
-#filtro para la barra del wget
-progressfilt ()
-{
-    local flag=false c count cr=$'\r' nl=$'\n'
-    while IFS='' read -d '' -rn 1 c
-    do
-        if $flag
-        then
-            printf '%c' "$c"
-        else
-            if [[ $c != $cr && $c != $nl ]]
-            then
-                count=0
-            else
-                ((count++))
-                if ((count > 1))
-                then
-                    flag=true
-                fi
-            fi
-        fi
-    done
-}
-
 failed=0
 work_dir=`mktemp -d --suffix=.update-firefox`
 moz_url='http://ftp.mozilla.org/pub/mozilla.org/firefox/releases/latest'
 echo "Descargando archivo de versiones"
 wget -q --show-progress -O "$work_dir/MD5SUMS" "$moz_url/MD5SUMS"
 
-moz_lang=`echo $LANG | cut -f 1 -d . | sed s/_/-/`
+if [ $? = 0 ];then
+	moz_lang=`echo $LANG | cut -f 1 -d . | sed s/_/-/`
 
-moz_arch=`uname -m`
-moz_link=`grep linux-$moz_arch/$moz_lang $work_dir/MD5SUMS |grep bz2`
+	# Si ejecutamos en un chroot problamente el idioma no este seleccionado
+	if [ "$moz_lang" = "C" ];then
+		echo "Forzando lenguaje es-AR"
+		moz_lang="es-AR"
+	fi
+	moz_arch=`uname -m`
+	moz_link=`grep linux-$moz_arch/$moz_lang $work_dir/MD5SUMS |grep bz2`
 
-moz_md5=`echo $moz_link | cut -f 1 -d " "`
-moz_path=`echo $moz_link | cut -f 2 -d " "`
-moz_file=`basename $moz_path`
+	moz_md5=`echo $moz_link | cut -f 1 -d " "`
+	moz_path=`echo $moz_link | cut -f 2 -d " "`
+	moz_file=`basename $moz_path`
 
-echo "$moz_md5 $work_dir/$moz_file" >> "$work_dir/VERIFY.MD5"
-echo "Descargando $moz_file...Aguarde un momento..."
-wget -q --show-progress -O "$work_dir/$moz_file" "$moz_url/$moz_path" 
-if [ $? = 0 ]; then
+	echo "$moz_md5 $work_dir/$moz_file" >> "$work_dir/VERIFY.MD5"
+	echo "Descargando $moz_file...Aguarde un momento..."
+	wget -q --show-progress -O "$work_dir/$moz_file" "$moz_url/$moz_path" 
+	if [ $? = 0 ]; then
 
-    #Archivo descargado, comprobar md5
-    echo "Verificando MD5"
-    md5sum -c "$work_dir/VERIFY.MD5"
+		#Archivo descargado, comprobar md5
+		echo "Verificando MD5"
+		md5sum -c "$work_dir/VERIFY.MD5"
 
-    if [ $? = 0 ]; then
-        echo "md5sum OK"
-        echo "Eliminado version anterior"
-        rm -rf /opt/firefox
-        echo "Descomprimiendo $moz_file...Aguarde un momento mas..."
-        tar xjf "$work_dir/$moz_file" -C "$work_dir"
-        mv "$work_dir/firefox" /opt    
-    else
-        echo "md5sum ERROR"
-        failed=1
-    fi
+		if [ $? = 0 ]; then
+			echo "md5sum OK"
+			echo "Eliminado version anterior"
+			rm -rf /opt/firefox
+			echo "Descomprimiendo $moz_file...Aguarde un momento mas..."
+			tar xjf "$work_dir/$moz_file" -C "$work_dir"
+			mv "$work_dir/firefox" /opt    
+		else
+			echo "md5sum ERROR"
+			failed=1
+		fi
+	else
+		echo "No se puede descargar el archivo $moz_file."
+		failed=1
+	fi
+
 else
-    echo "No se puede descargar el archivo $moz_file."
-    failed=1
+	echo "Error al descargar archivo de versiones. Esta conectado a internet?"
+	failed=1
 fi
 
 if [ $failed = 0 ]; then
